<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pnconfig" nsURI="http://es.unizar.disco/pnconfig/1.0" nsPrefix="pnconfig">
  <eClassifiers xsi:type="ecore:EClass" name="PetriNetConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="analysisType" lowerBound="1"
        eType="#//AnalysisType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableAssignments" upperBound="-1"
        eType="#//EStringToEFloatObjectsMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialMarking" lowerBound="1"
        eType="#//EStringToEFloatObjectsMap"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AnalysisType">
    <eLiterals name="transient"/>
    <eLiterals name="steadyState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EStringToEFloatObjectsMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
  </eClassifiers>
</ecore:EPackage>
