<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="definition" nsURI="http://es.unizar.disco/simulation/definition/1.0"
    nsPrefix="definition">
  <eClassifiers xsi:type="ecore:EClass" name="SimulationDefinition">
    <eOperations name="getVariables">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Aggregation of the {@link #getInputVariables()} and {@link #getOutputVariables()} {@link EStructuralFeature}s as a single {@link Collection}.&#xD;&#xA;Changes in the {@link Collection} are reflected in the underlying {@link EStructuralFeature}."/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType datatypes.ecore#//Collection">
        <eTypeArguments eClassifier="#//Variable"/>
      </eGenericType>
    </eOperations>
    <eOperations name="getVariablesMap">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="{@link Map} view of the {@link Collection} returned by {@link getVariables}.&#xD;&#xA;Changes in the {@link Map} are reflected in the underlying {@link Collection} and thus, to the underlying {@link EStructuralFeature}s."/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eTypeArguments eClassifier="#//Variable"/>
      </eGenericType>
    </eOperations>
    <eOperations name="getInputVariablesMap">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="{@link Map} view of the {@link getInputVariables} {@link EStructuralFeature}.&#xD;&#xA;Changes in the {@link Map} are reflected in the underlying {@link EStructuralFeature}."/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eTypeArguments eClassifier="#//InputVariable"/>
      </eGenericType>
    </eOperations>
    <eOperations name="getOutputVariablesMap">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="{@link Map} view of the {@link getOutputVariables} {@link EStructuralFeature}.&#xD;&#xA;Changes in the {@link Map} are reflected in the underlying {@link EStructuralFeature}."/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eTypeArguments eClassifier="#//OutputVariable"/>
      </eGenericType>
    </eOperations>
    <eOperations name="syncScenarios">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Synchronize the &lt;code>Scenarios&lt;/code> information from the current {@link SimulationDefinition} {@link Resource}"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="syncVariables">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Synchronize the {@link Variable}s information from the &lt;code>Scenario&lt;/code> returned by {@link #getActiveScenario()}"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="syncDomainMeasureDefinitions">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Synchronize the {@link DomainMeasuresDefinition}s information from the &lt;code>Scenario&lt;/code> returned by {@link #getActiveScenario()}"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="syncPossibleVariableConfigurations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" derived="true"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invocations" upperBound="-1"
        eType="ecore:EClass invocation.ecore#//SimulationInvocation" derived="true"
        eOpposite="invocation.ecore#//SimulationInvocation/definition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//SimulationParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activeScenario" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" lowerBound="1"
        upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputVariables" ordered="false"
        upperBound="-1" eType="#//InputVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainResource" lowerBound="1"
        eType="ecore:EClass datatypes.ecore#//Resource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxExecutionTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate" defaultValueLiteral="0000-00-00'01:00:00"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputVariables" ordered="false"
        upperBound="-1" eType="#//OutputVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaredMeasures" lowerBound="1"
        upperBound="-1" eType="ecore:EClass measures.ecore#//DomainMeasureDefinition"
        containment="true" eOpposite="measures.ecore#//DomainMeasureDefinition/simulationDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measuresToCompute" lowerBound="1"
        upperBound="-1" eType="ecore:EClass measures.ecore#//DomainMeasureDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="backend" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="possibleConfigurations"
        upperBound="-1" eType="#//VariableConfiguration" derived="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activeConfigurations" upperBound="-1"
        eType="#//VariableConfiguration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autoSync" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" transient="true"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scenarioStereotypes" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nfpToCompute" eType="ecore:EEnum datatypes.ecore#//ComputableNFPtype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimulationParameter" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputVariable" eSuperTypes="#//Variable">
    <eOperations name="deserializeValues">
      <eParameters name="values" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="serializeValues" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" lowerBound="1"
        upperBound="-1" eType="#//InputVariableValue" containment="true" eOpposite="#//InputVariableValue/variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignments" lowerBound="1"
        upperBound="-1" eType="#//VariableAssignment" eOpposite="#//VariableAssignment/variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputVariable" eSuperTypes="#//Variable"/>
  <eClassifiers xsi:type="ecore:EClass" name="InputVariableValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType datatypes.ecore#//Number"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignments" lowerBound="1"
        upperBound="-1" eType="#//VariableAssignment" eOpposite="#//VariableAssignment/value"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//InputVariable" eOpposite="#//InputVariable/values"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableAssignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//InputVariableValue"
        eOpposite="#//InputVariableValue/assignments"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" lowerBound="1"
        eType="#//VariableConfiguration" eOpposite="#//VariableConfiguration/assignments"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//InputVariable" eOpposite="#//InputVariable/assignments"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableConfiguration">
    <eOperations name="isEquivalent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="config" eType="#//VariableConfiguration"/>
    </eOperations>
    <eOperations name="toPrimitiveAssignments" upperBound="-1" eType="ecore:EClass datatypes.ecore#//PrimitiveVariableAssignment"/>
    <eOperations name="findAssignment" eType="#//VariableAssignment">
      <eParameters name="variable" eType="#//InputVariable"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignments" lowerBound="1"
        upperBound="-1" eType="#//VariableAssignment" containment="true" eOpposite="#//VariableAssignment/configuration"/>
  </eClassifiers>
</ecore:EPackage>
