<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="invocation" nsURI="http://es.unizar.disco/simulation/invocation/1.0"
    nsPrefix="invocation">
  <eClassifiers xsi:type="ecore:EClass" name="SimulationInvocation">
    <eOperations name="buildAnalyzableModel" eType="ecore:EDataType datatypes.ecore#//IStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" derived="true"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceSet" eType="ecore:EClass traces.ecore#//TraceSet"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toolResult" eType="ecore:EClass toolresult.ecore#//ToolResult"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" lowerBound="1"
        eType="ecore:EClass definition.ecore#//SimulationDefinition" eOpposite="definition.ecore#//SimulationDefinition/invocations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" eType="ecore:EClass simresult.ecore#//SimulationResult"
        eOpposite="simresult.ecore#//SimulationResult/invocation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EEnum datatypes.ecore#//SimulationStatus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableConfiguration"
        lowerBound="1" eType="ecore:EClass definition.ecore#//VariableConfiguration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="analyzableModel" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autoBuild" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" transient="true"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invocationSet" eType="#//InvocationSet"
        eOpposite="#//InvocationSet/invocations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvocationsRegistry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="invocationSets" upperBound="-1"
        eType="#//InvocationSet" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvocationSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="invocations" lowerBound="1"
        upperBound="-1" eType="#//SimulationInvocation" eOpposite="#//SimulationInvocation/invocationSet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" lowerBound="1"
        eType="ecore:EClass definition.ecore#//SimulationDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EEnum datatypes.ecore#//SimulationStatus"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
</ecore:EPackage>
