<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="measures" nsURI="http://es.unizar.disco/simulation/measures/1.0"
    nsPrefix="measures">
  <eClassifiers xsi:type="ecore:EClass" name="DomainMeasure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType datatypes.ecore#//Number"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="unspecified"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" lowerBound="1"
        eType="#//DomainMeasureDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeasureCalculator" instanceClassName="es.unizar.disco.simulation.models.measures.MeasureCalculator"
      abstract="true" interface="true">
    <eOperations name="calculate" eType="#//DomainMeasure">
      <eParameters name="domainElement" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="definition" eType="#//DomainMeasureDefinition"/>
      <eParameters name="toolResult" eType="ecore:EClass toolresult.ecore#//ToolResult"/>
      <eParameters name="traceSet" eType="ecore:EClass traces.ecore#//TraceSet"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainMeasureDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="measuredElement" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="measure" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vslExpressionEntries" upperBound="-1"
        eType="#//Entry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vslExpression" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" volatile="true"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputVariable" lowerBound="1"
        eType="ecore:EClass definition.ecore#//OutputVariable" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simulationDefinition" lowerBound="1"
        eType="ecore:EClass definition.ecore#//SimulationDefinition" eOpposite="definition.ecore#//SimulationDefinition/declaredMeasures"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
