<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="wnsim" nsURI="http://es.unizar.disco/simulation/tool/wnsim/1.0"
    nsPrefix="wnsim">
  <eClassifiers xsi:type="ecore:EEnum" name="SimulationParameters">
    <eLiterals name="first_tr_length" literal="-f"/>
    <eLiterals name="tr_length" value="1" literal="-t"/>
    <eLiterals name="min_btc" value="2" literal="-m"/>
    <eLiterals name="max_btc" value="3" literal="-M"/>
    <eLiterals name="approx" value="4" literal="-a"/>
    <eLiterals name="conf_level" value="5" literal="-c"/>
    <eLiterals name="seed" value="6" literal="-s"/>
    <eLiterals name="start" value="7" literal="-o"/>
    <eLiterals name="binary_file_path" value="10"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WnsimResult" eSuperTypes="toolresult.ecore#//ToolResult"/>
  <eClassifiers xsi:type="ecore:EClass" name="WnsimElementInfo" abstract="true" eSuperTypes="toolresult.ecore#//AnalyzableElementInfo"/>
  <eClassifiers xsi:type="ecore:EClass" name="PlaceInfo" eSuperTypes="#//WnsimElementInfo">
    <eOperations name="getValue" eType="ecore:EDataType datatypes.ecore#//Number">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return meanNumberOfTokens;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="meanNumberOfTokens" eType="ecore:EDataType datatypes.ecore#//Number"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransitionInfo" eSuperTypes="#//WnsimElementInfo">
    <eOperations name="getValue" eType="ecore:EDataType datatypes.ecore#//Number">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return throughput;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="throughput" eType="ecore:EDataType datatypes.ecore#//Number"/>
  </eClassifiers>
</ecore:EPackage>
