<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="datatypes" nsURI="http://es.unizar.disco/simulation/datatypes/1.0"
    nsPrefix="datatypes">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="conversionDelegates" value="http://es.unizar.disco/simulation/conversion/number/1.0 http://es.unizar.disco/simulation/conversion/uri/1.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EDataType" name="URI" instanceClassName="org.eclipse.emf.common.util.URI">
    <eAnnotations source="http://es.unizar.disco/simulation/conversion/uri/1.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Number" instanceClassName="java.lang.Number">
    <eAnnotations source="http://es.unizar.disco/simulation/conversion/number/1.0">
      <details key="conversionDelegates" value="http://es.unizar.disco/simulation/conversion/1.0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IStatus" instanceClassName="org.eclipse.core.runtime.IStatus"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Collection" instanceClassName="java.util.Collection">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SimulationStatus">
    <eLiterals name="unknown" literal="Unknown"/>
    <eLiterals name="running" value="1" literal="Running"/>
    <eLiterals name="finished" value="2" literal="Finished"/>
    <eLiterals name="killed" value="3" literal="Killed"/>
    <eLiterals name="waiting" value="4" literal="Waiting"/>
    <eLiterals name="failed" value="5" literal="Failed"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" lowerBound="1" eType="#//URI"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resource" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResource"
        changeable="false" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveVariableAssignment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variable" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="#//Number"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NonStandardUnits">
    <eLiterals name="unspecified"/>
    <eLiterals name="percentage" value="1"/>
    <eLiterals name="tick" value="2"/>
    <eLiterals name="events_per_tick" value="3"/>
  </eClassifiers>
</ecore:EPackage>
