<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="measures" nsURI="http://es.unizar.disco/simulation/measures/1.0"
    nsPrefix="measures">
  <eClassifiers xsi:type="ecore:EClass" name="DomainMeasure" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType datatypes.ecore#//Number"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measuredElement" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" lowerBound="1" eType="ecore:EEnum datatypes.ecore#//Unit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Throughput" eSuperTypes="#//DomainMeasure">
    <eOperations name="getValue" eType="ecore:EDataType datatypes.ecore#//Number">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return throughput;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="throughput" lowerBound="1"
        eType="ecore:EDataType datatypes.ecore#//Number"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResponseTime" eSuperTypes="#//DomainMeasure">
    <eOperations name="getValue" eType="ecore:EDataType datatypes.ecore#//Number">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return responseTime;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseTime" lowerBound="1"
        eType="ecore:EDataType datatypes.ecore#//Number"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Utilization" eSuperTypes="#//DomainMeasure">
    <eOperations name="getValue" eType="ecore:EDataType datatypes.ecore#//Number">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return utilization;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="utilization" lowerBound="1"
        eType="ecore:EDataType datatypes.ecore#//Number"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeasureConverter" abstract="true" interface="true">
    <eOperations name="convert"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//DomainMeasure"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="ecore:EClass toolresult.ecore#//AnalyzableElementInfo"/>
  </eClassifiers>
</ecore:EPackage>
