<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simresult" nsURI="http://es.unizar.disco/simulation/simresult/1.0"
    nsPrefix="simresult">
  <eClassifiers xsi:type="ecore:EClass" name="SimulationResult">
    <eStructuralFeatures xsi:type="ecore:EReference" name="invocation" lowerBound="1"
        eType="ecore:EClass invocation.ecore#//SimulationInvocation" eOpposite="invocation.ecore#//SimulationInvocation/results"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measures" upperBound="-1"
        eType="ecore:EClass measures.ecore#//DomainMeasure" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
